### ISSUE TITLE
Makefile 

### ISSUE THREAD

**Issue by sje30** [singlesourcepub/jats-from-markdown#3]
hi,

the first target in Makefile, paper.jats.xml, has paper.md as a dependenc, but paper.md is missing.  Should this be talks.md?

If I copy talks.md to paper.md 'make' then works correctly and I get my first .jats.xml file thank you!

**Comment by tarleb** [comment]
Sorry, my bad. I renamed paper.md to index.md – so it can be viewed through https://singlesourcepub.github.io/jats-from-markdown – and forgot to update the Makefile. Should be fixed now.
